name: Github Actions Terraform
on: [push]
jobs:
  format_check:
    name: Terraform Validation Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: load backend configuration
        run: echo $BACKEND_CONFIG > backend.conf
        env:
          BACKEND_CONFIG: ${{ vars.backend_file_contents }}

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        run: terraform init -backend-config=backend.conf

      - name: Terraform Validate
        run: terraform validate -no-color

      